### ISSUE TITLE
target origin and instanceid are not set

### ISSUE THREAD

**Issue by pherbel** [forcedotcom/SalesforceCanvasJavascriptSDK#6]
The example describes which information is coming in the callback url, but the code will not be able to set the target_origin and instance_id because these information are not provided or the identifiers are different.

 /*\* 
198          *@private 
199          */ 
200             // Example Results of tha hash.... 
201             // Name [access_token] Value [00DU0000000Xthw!ARUAQMdYg9ScuUXB5zPLpVyfYQr9qXFO7RPbKf5HyU6kAmbeKlO3jJ93gETlJxvpUDsz3mqMRL51N1E.eYFykHpoda8dPg_z] 
202             // Name [instance_url] Value [https://na12.salesforce.com] 
203             // Name [id] Value [https://login.salesforce.com/id/00DU0000000XthwMAC/005U0000000e6PoIAI] 
204             // Name [issued_at] Value [1331000888967] 
205             // Name [signature] Value [LOSzVZIF9dpKvPU07icIDOf8glCFeyd4vNGdj1dhW50] 
206             // Name [state] Value [/crazyrefresh.html] 
207         function parseHash(hash) { 
208             var i, nv, nvp, n, v; 
209 

210             if (! $$.isNil(hash)) { 
211                 if (hash.indexOf('#') === 0) { 
212                     hash = hash.substr(1); 
213                 } 
214                 nvp = hash.split("&"); 
215 

216                 for (i = 0; i < nvp.length; i += 1) { 
217                     nv = nvp[i].split("="); 
218                     n = nv[0]; 
219                     v = decodeURIComponent(nv[1]); 
220                     if ("access_token" === n) { 
221                         token(v); 
222                     } 
223                     else if ("instance_url" === n) { 
224                         instanceUrl(v); 
225                     } 
226                     else if ("target_origin" === n) { 
227                         tOrigin = decodeURIComponent(v); 
228                     } 
229                     else if ("instance_id" === n) { 
230                         instId = v; 
231                     } 
232                 } 
233             } 
234         }

**Comment by mpsenn** [comment]
I'm not quite sure if this is still an issue. The code looks correct to me. I'd be glad to take another look if you point to a more specific line of code.
